# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
security:
  # https://symfony.com/doc/current/security.html

  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: "^/(_(profiler|wdt)|css|images|js)/"
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        invalidate_session: true

  access_control:
    - { path: "^/login$", roles: PUBLIC_ACCESS }
    - { path: "^/register$", roles: PUBLIC_ACCESS }
    - { path: "^/", roles: PUBLIC_ACCESS }
