<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520113053 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(100) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_admin BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE blog_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_published BOOLEAN DEFAULT true NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA5AE01DF675F31B ON blog_post (author_id)');
        $this->addSql('CREATE TABLE breathing_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, inhale_seconds INT NOT NULL, hold_seconds INT NOT NULL, exhale_seconds INT NOT NULL, cycles INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C813B9A1B03A8386 ON breathing_exercise (created_by_id)');
        $this->addSql('CREATE TABLE emotion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DEBC77727ACA70 ON emotion (parent_id)');
        $this->addSql('CREATE TABLE emotion_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, emotion_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A482672A1EE4A582 ON emotion_entry (emotion_id)');
        $this->addSql('CREATE INDEX IDX_A482672AA76ED395 ON emotion_entry (user_id)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01DF675F31B FOREIGN KEY (author_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE breathing_exercise ADD CONSTRAINT FK_C813B9A1B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE emotion ADD CONSTRAINT FK_DEBC77727ACA70 FOREIGN KEY (parent_id) REFERENCES emotion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE emotion_entry ADD CONSTRAINT FK_A482672A1EE4A582 FOREIGN KEY (emotion_id) REFERENCES emotion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE emotion_entry ADD CONSTRAINT FK_A482672AA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blog_post DROP CONSTRAINT FK_BA5AE01DF675F31B');
        $this->addSql('ALTER TABLE breathing_exercise DROP CONSTRAINT FK_C813B9A1B03A8386');
        $this->addSql('ALTER TABLE emotion DROP CONSTRAINT FK_DEBC77727ACA70');
        $this->addSql('ALTER TABLE emotion_entry DROP CONSTRAINT FK_A482672A1EE4A582');
        $this->addSql('ALTER TABLE emotion_entry DROP CONSTRAINT FK_A482672AA76ED395');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE blog_post');
        $this->addSql('DROP TABLE breathing_exercise');
        $this->addSql('DROP TABLE emotion');
        $this->addSql('DROP TABLE emotion_entry');
    }
}
